Repository The-CS-Nerds/Library-System, pull requests merged in 2025-07, with the labels that each got.

#21 Update Security.md to more accurately reflect policy
  SECURITY.md
Labels: documentation

#28 README updating
  README.md
Labels: documentation

#36 Propagate README back to dev
  README.md
Labels: documentation

#39 Update README.md to show docker usage
  README.md
Labels: enhancement

#49 Clarify that we're talking about physical libraries
  README.md
Labels: documentation

#67 Example Casbin User Table
  db-init/1_tables.sql
  src/backend/auth/codel.conf
Labels: example

#71 Merge all the updates from dev
  compose.yaml
  src/backend/__main__.py
  src/backend/auth/model.conf
  src/backend/backend.Dockerfile
  src/backend/configuration.env
  src/backend/db.py
  src/backend/requirements.in
  src/backend/requirements.txt
  src/frontend/configuration.env
  src/frontend/frontend.Dockerfile
  src/frontend/requirements.in
  src/frontend/requirements.txt
Labels: enhancement

#87 Patch a few issues in dev
  docker-entrypoint.sh
  src/backend/auth/policySetup.py
  src/backend/db.py
Labels: bug

#108 Fixes the error with `DSN.delete()`
  src/backend/auth/policySetup.py
Labels: bug

#110 Users patch
  db-init/1_tables.sql
  src/backend/backend.Dockerfile
  src/backend/db.py
  src/backend/requirements.in
Labels: S-High, T-Task, P-0, C-Backend, L-Python
